//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPullSource
    {
        public int pullSourceId { get; set; }
        public string sourcePath { get; set; }
        public Nullable<int> waterPlantId { get; set; }
        public Nullable<int> treatmentStepTypeId { get; set; }
        public Nullable<int> qualityIndicatortypeId { get; set; }
        public string dataType { get; set; }
    }
}
