//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class vQualityIndicatorTypeMapping
    {
        public int indicatorTypeId { get; set; }
        public string realIndicatorName { get; set; }
        public string indicatorAlias { get; set; }
    }
}
