//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class vWaterPlantPropertyMapper
    {
        public int waterPlantId { get; set; }
        public string nameOnWaterplant { get; set; }
        public string realName { get; set; }
        public string waterPlantName { get; set; }
        public int locationId { get; set; }
        public int supplierId { get; set; }
    }
}
